apiVersion: v1
kind: Pod
metadata:
  name: startup-demo
  labels:
    app: probes-demo
spec:
  containers:
  - name: busybox
    image: busybox
    
    args:
    - /bin/sh
    - -c
    - | 
      sleep 40;
      touch /tmp/started;
      sleep 600;
    
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/started
      
      failureThreshold: 30
      periodSeconds: 5
  

