apiVersion: v1
kind: Pod
metadata: 
  name: pod-b
  namespace: ns-b
  labels: 
    app: pod-b
spec:
  containers:
  - image: alpine
    name: pod-b
    command: ["/bin/sh", "-c", "sleep 3600"]
  restartPolicy: Never
    
