apiVersion: v1
kind: Pod
metadata: 
  name: example-pod
  namespace: dev
  labels:
    app: example
spec:
  containers:
  - image: nginx
    name: example-contianer
    ports:
    - containerPort: 80
