#Equivalent of running POD kubectl run nginx-pod --image=nginx:1.27.0

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-test
  labels:
    env: test
spec:
  containers:
  - name: nginx-container
    image: nginx:1.27.0
    ports:
      - containerPort: 80
