apiVersion: v1
kind: Pod
metadata:
  name: myapp-frontend
  labels:
    app: myapp
    tier: frontend
    environment: development
    release: snapshot
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
