apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-antiaffinity-demo-depl
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pod-antiaffinity
  template:
    metadata:
      labels:
        app: pod-antiaffinity
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pod-antiaffinity
            topologyKey: kubernetes.io/hostname
      containers:
      - name: myapp
        image: nginx

