apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-demo
  type: NodePort   # use ClusterIP if internal only
  ports:
  - name: nginx-80
    port: 80
    targetPort: 80
    nodePort: 30080

  - name: nginx-81
    port: 81
    targetPort: 81
    nodePort: 30081

