apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
  labels:
    app: empty-dir-pod
spec:
  containers:
  - name: empty-dir-pod-c
    image: busybox
    command:
      - "sh"
      - "-c"
      - "sleep 3600"
    volumeMounts:
    - name: temp-storage
      mountPath: /usr/share/temp
  volumes:
  - name: temp-storage
    emptyDir: {} 

