apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-example
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ['minikube']

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage

---
apiVersion: v1
kind: Pod
metadata:
  name: persistent-volume-pod
  labels:
    app: persistent-volume-pod
spec:
  containers:
  - name: persistent-volume-pod1
    image: busybox
    command:
      - "sh"
      - "-c"
      - "sleep 3600"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: persistent-volume
        mountPath: /mnt/local
  volumes:
    - name: persistent-volume
      persistentVolumeClaim:
        claimName: persistent-volume-claim

  

