apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes-example
  labels:
    app: pod-volumes-example
spec:
  containers:
  - name: empty-dir-writer
    image: busybox
    command:
      - "sh"
      - "-c"
      - "sleep 3600"
    volumeMounts:
    - name: temporary-storage
      mountPath: /usr/share/temp

  - name: pod-volumes-reader
    image: busybox
    command:
      - "sh"
      - "-c"
      - "sleep 3600"
    volumeMounts:
    - name: temporary-storage
      mountPath: /temp
      readOnly: true
  volumes:
  - name: temporary-storage
    emptyDir: {}
