apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: "info"
  DB_HOST: "Ppostgres-service"
  APP_PORT: "8080"
  ##Multiline entry
  app.properties: |
    server.port=80
    spring.datasource.url=jdbc:postgresssql://postgres-service:5432/mydb
    logging.level.root=INFO