apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-demo
  labels:
    app: empty-dir-demo
spec:
  containers:
  - name: empty-dir-write
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
    volumeMounts:
    - name: empty-dir
      mountPath: /usr/share/temp
  - name: empty-dir-read
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
    volumeMounts:
    - name: empty-dir
      mountPath: /temp
      readOnly: true
  volumes:
  - name: empty-dir
    emptyDir: {}

