apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  capacity:
    storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values: ["minikube"]

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-pvc
spec:
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage

---

apiVersion: v1
kind: Pod
metadata:
  name: loval-volume-pod
  labels:
    app: local-volume-demo
spec:
  containers:
  - name: local-volume-pod
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: local-volume
      mountPath: /mtn/local
  volumes:
  - name: local-volume
    persistentVolumeClaim:
      claimName: local-volume-pvc

