apiVersion: v1
kind: Pod
metadata:
  name: cm-env-demo
  labels:
    app: cm-env-demo
spec:
  containers:
  - name: cm-demo
    image: busybox
    command: ["sh", "-c", "env | grep -E 'LOG|DB|PORT'; sleep 3600"]
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: LOG_LEVEL
    envFrom:
    - configMapRef:
        name: app-config
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

