version: '3.8'

services: 
  web:    
    image: nginx:latest   
    ports:     
      - "80:80"   
    networks:      
      - frontend    
    volumes:      
      - ./app:/usr/share/nginx/html
    depends_on:
      - app

  app:   
    image: node:14   
    working_dir: /app  
    command: node server.js   # Specify a command
    networks:     
      - frontend    
    volumes:      
      - ./app:/app

networks:  
  frontend:   
    driver: bridge

volumes:  
  shared-volume: