apiVersion: v1
kind: Pod
metadata:
  name: k8s-probes-demo
spec:
  containers:
    - name: k8s-probes-demo
      image: pawanhb/simplenodeapp-ks:1.1.0 # An image that has a delayed readiness endpoint
      ports:
      - containerPort: 3000
      readinessProbe:
        httpGet:
          path: /ready # The endpoint that signals readiness
          port: 3000
        initialDelaySeconds: 2 # Wait 2 seconds before the first probe
        periodSeconds: 3       # Check every 3 seconds thereafter
        failureThreshold: 3    # Mark as not ready after 3 consecutive failures

