apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-demo
spec:
  containers:
  - image: busybox
    command: ['sh', '-c', 'echo "starting application..."; sleep 30; touch /tmp/startup-file; sleep 3600']
    name: startup-probe-demo
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/startup-file
      initialDelaySeconds: 2
      periodSeconds: 5
      failureThreshold: 2
      timeoutSeconds: 1
   
